from enum import Enum

from sc2.ids.unit_typeid import UnitTypeId as UnitID

COMMON_UNIT_IGNORE_TYPES: set[UnitID] = {UnitID.EGG, UnitID.LARVA, UnitID.BROODLING}


class RequestType(str, Enum):
    ADD_TO_QUEUE = "ADD_TO_QUEUE"
    GET_ARE_QUEUES_EMPTY = "GET_ARE_QUEUES_EMPTY"
    GET_ARMY_COMP = "GET_ARMY_COMP"
    GET_ATTACK_TARGET = "GET_ATTACK_TARGET"
    GET_IS_AGGRESSIVE = "GET_IS_AGGRESSIVE"
    GET_IS_ITEM_IN_QUEUE = "GET_IS_ITEM_IN_QUEUE"
    GET_NEXT_EXPANSION_LOCATION = "GET_NEXT_EXPANSION_LOCATION"
    GET_RALLY_POINT = "GET_RALLY_POINT"
    GET_REAPER_SCOUT_FINISHED = "GET_REAPER_SCOUT_FINISHED"
    GET_TANK_TO_NEW_POSITION_DICT = "GET_TANK_TO_NEW_POSITION_DICT"
    REQUEST_SCAN = "REQUEST_SCAN"
